### ISSUE TITLE
Built-in `ignoreRules` 

### ISSUE THREAD

**Issue by romaricpascal** [rhumaric/stylelint-plugin-prefer-utility#2]
Without a decent `ignoreRules`, some selectors that would legitimately have only one declaration would be caught. For example:

```css
// Element selectors
* {
  box-sizing: border-box;
}
// Pseudo classes
a:hover {
  text-decoration: underline;
}
// Pseudo elements
.something::before {
  display: none;
}
// Attribute selectors
[aria-current="page"] {
  border-bottom: solid 2px;
}
```
Two questions:
 - what would be a good default to ignore? Single classes and IDs sound a good starting point. Is it too wide or too specific though?
 - how should it play with the `ignoreRules` option? Would the option override or just complement it? Actually a better option might be to expose a function as `stylelint-plugin-prefer-utility/ignoreRules` and have it used by default in the recommended configuration?
